version: "2"
linters-settings:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 30
  misspell:
    locale: US

linters:
  enable:
    - unused
    - errcheck
    - gocognit
    - gocyclo
    - govet
    - misspell
    - staticcheck
    - whitespace
