name: Run Go Tests in DevContainer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  devcontainer-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/yuyahy/learn_go_with_tests
          runCmd: go test ./...